// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctoqhpshwetpjsenursk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0b3FocHNod2V0cGpzZW51cnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQwMDIsImV4cCI6MjA2MzU4MDAwMn0.fHO9DviPDTHgmPULXeYydg_1H8jAmTAcmYi1OmcXZeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);